# Generated by Django 5.2.5 on 2025-08-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(max_length=12)),
                ('color', models.CharField(max_length=12)),
                ('tomat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.tomat')),
            ],
        ),
    ]
