# Generated by Django 5.2.5 on 2025-09-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
