# Generated by Django 5.2.5 on 2025-09-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_tomat_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField()),
                ('addres', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('IN_WORK', 'В обработке'), ('FINISH', 'Готов')])),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.client')),
                ('tomats', models.ManyToManyField(to='first.tomat')),
            ],
        ),
    ]
